#
# Copyright [2025] Threat Patrols Pty Ltd (https://www.threatpatrols.com)
#

name: 'Get PyPi recent packages'
description: 'Query Click House public pypi.projects table for PyPi projects that have new package file uploads.'
author: 'Threat Patrols'

inputs:
  output_file:
    description: 'File to save output report data into [default: pypi-virgin-packages.json]'
    default: 'pypi-virgin-packages.json'
  query_interval_seconds:
    description: 'Query time interval from now() until interval seconds ago [default: <172800 = 48 hours>]'
    default: '172800'
  clickhouse_url:
    description: 'Click House data source URL [default: <clickhouse public data server>]'
    default: 'https://sql-clickhouse.clickhouse.com/'
  clickhouse_username:
    description: 'Click House username [default: demo]'
    default: 'demo'
  clickhouse_password:
    description: 'Click House password [default: <empty>]'
    default: ''

outputs:
  output_file:
    description: "File where output report data has been saved."

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: 'package'
  color: 'blue'
